:Author: jcampo
:Email: {AuthorEmail}
:Date: 18/04/2020
:Revision: version#
:License: Public Domain

= Project: {Sensor de aparcamiento para vehículos}

Sensor que se encarga de medir la distancia del coche con el objeto que disponga detrás, para facilitar al conductor la maniobra de aparcamiento, a través de una señal acústica y tres leds de color para indicar la alerta.

== Step 1: Installation
No precisa instalación de ninguna librería

1. Descarga el código
2. Edita los valores de distancia como mejor desees en las variables definidas para cada alerta (umbral1, umbral2, umbral3)

== Step 2: Assemble the circuit

Ensambla el circuito de la siguiente manera layout.png

== Step 3: Carga el código

Sube el código contenido en este sketch a tu placa de arduino

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── layout.png          => imagen con el cableado de conexión
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact jcampo https://id.arduino.cc/jcampo

=== BOM
Materiales necesarios para el proyecto.

|===
| ID | Part name      | Part number | Quantity
| S1 | HC-SR04        | ---------   | 1
| MB | PROTOBOARD     | ---------   | 1
| R1 | 220k Resistor  | ---------   | 3
| D1 | Red LED        | ---------   | 1
| D2 | Yellow LED     | ---------   | 1
| D3 | Green LED      | ---------   | 1
| A1 | Arduino UNO    | ---------   | 1
| BZ | BUZZER         | ---------   | 1
|===

